# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: commited

#on:
#  workflow_dispatch:
#  pull_request:
#    types: [ labeled ]
on:
  workflow_dispatch:

env:
    CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.THOUGHTSPOT_URL_DEV }}
    CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.THOUGHTSPOT_USERNAME_DEV }}
    CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.THOUGHTSPOT_SECRET_KEY_DEV }}
    #CS_TOOLS_THOUGHTSPOT____DEFAULT_ORG: ${{ secrets.THOUGHTSPOT_DEFAULT_ORG }}
    

jobs:
  
  commit_to_github:
    #if: ${{ github.event.label.name == 'approved' }} 
    #if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'approved')  
    runs-on: ubuntu-latest
    steps:
      - name: checking prod branch
        uses: actions/checkout@v4
        with:
          ref: dev2
          
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install cs_tools
        run: python -m pip install "cs_tools[cli] @ https://github.com/thoughtspot/cs_tools/archive/v1.5.10.zip"

      - name: Install Pydantic-Setting requirements
        run: python -m pip install pydantic-settings==2.5.2

      - name: run the deploy command
        run: "cs_tools tools git branches commit --tag ready --comment test --org 1980614359 --config ENV:"
