name: Validate Changes

on:
  # ALLOW TRIGGERING ACTION ONLY SPECIFIC PRs
  pull_request:
    paths:
      - '.github/PULL_REQUEST_TEMPLATE/request_merge_thoughtspot_changes.md'

env:
  # CS TOOLS IS COMMAND LINE LIBRARY WRAPPING TS APIS
  # https://thoughtspot.github.io/cs_tools/tools/git/
  CS_TOOLS_VERSION: v1.5.12
  CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.THOUGHTSPOT_URL }}
  CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.THOUGHTSPOT_USERNAME }}
  CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.THOUGHTSPOT_SECRET_KEY }}


jobs:

  run_validate_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out ${{ env.TS_ENV_NAME }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TS_ENV_NAME }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
  
      - name: Install CS Tools
        run: pip install "cs_tools[cli] @ https://github.com/thoughtspot/cs_tools/archive/${{ env.CS_TOOLS_VERSION }}.zip"

      - name: run the deploy command
        run: "cs_tools tools git branches validate --source_branch ${{ github.head_ref }} --target_branch ${{ github.base_ref }} --config ENV:"
